# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Divine-Gate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Divine-Gate
　import RealmSwift

  target 'Divine-GateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Divine-GateUITests' do
    # Pods for testing
  end

end
